const VERSES = [
  { ref: "Genesis 1:1", text: "In the beginning God created the heavens and the earth." },
  { ref: "Exodus 14:14", text: "The Lord himself will fight for you. Just stay calm." },
  { ref: "Deuteronomy 31:6", text: "So be strong and courageous! Do not be afraid and do not panic before them. For the Lord your God will personally go ahead of you." },
  { ref: "Joshua 1:9", text: "This is my command—be strong and courageous! Do not be afraid or discouraged. For the Lord your God is with you wherever you go." },
  { ref: "Ruth 1:16", text: "Wherever you go, I will go; wherever you live, I will live. Your people will be my people, and your God will be my God." },
  { ref: "Psalm 23:1", text: "The Lord is my shepherd; I have all that I need." },
  { ref: "Psalm 27:1", text: "The Lord is my light and my salvation—so why should I be afraid?" },
  { ref: "Psalm 46:1", text: "God is our refuge and strength, always ready to help in times of trouble." },
  { ref: "Psalm 91:2", text: "This I declare about the Lord: He alone is my refuge, my place of safety; he is my God, and I trust him." },
  { ref: "Proverbs 3:5-6", text: "Trust in the Lord with all your heart; do not depend on your own understanding. Seek his will in all you do, and he will show you which path to take." },
  { ref: "Isaiah 40:31", text: "But those who trust in the Lord will find new strength. They will soar high on wings like eagles. They will run and not grow weary. They will walk and not faint." },
  { ref: "Isaiah 41:10", text: "Don’t be afraid, for I am with you. Don’t be discouraged, for I am your God. I will strengthen you and help you." },
  { ref: "Jeremiah 29:11", text: "For I know the plans I have for you, says the Lord. They are plans for good and not for disaster, to give you a future and a hope." },
  { ref: "Matthew 5:16", text: "In the same way, let your good deeds shine out for all to see, so that everyone will praise your heavenly Father." },
  { ref: "Matthew 6:33", text: "Seek the Kingdom of God above all else, and live righteously, and he will give you everything you need." },
  { ref: "Matthew 11:28", text: "Then Jesus said, 'Come to me, all of you who are weary and carry heavy burdens, and I will give you rest.'" },
  { ref: "John 3:16", text: "For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life." },
  { ref: "John 8:12", text: "I am the light of the world. If you follow me, you won’t have to walk in darkness, because you will have the light that leads to life." },
  { ref: "Romans 8:28", text: "And we know that God causes everything to work together for the good of those who love God and are called according to his purpose for them." },
  { ref: "Romans 12:2", text: "Don’t copy the behavior and customs of this world, but let God transform you into a new person by changing the way you think." },
  { ref: "1 Corinthians 13:4-7", text: "Love is patient and kind. Love is not jealous or boastful or proud or rude..." },
  { ref: "2 Corinthians 5:17", text: "This means that anyone who belongs to Christ has become a new person. The old life is gone; a new life has begun!" },
  { ref: "Philippians 4:6-7", text: "Don’t worry about anything; instead, pray about everything. Tell God what you need, and thank him for all he has done." },
  { ref: "Philippians 4:13", text: "For I can do everything through Christ, who gives me strength." },
  { ref: "2 Timothy 1:7", text: "For God has not given us a spirit of fear and timidity, but of power, love, and self-discipline." },
  { ref: "Hebrews 11:1", text: "Faith shows the reality of what we hope for; it is the evidence of things we cannot see." },
  { ref: "1 Peter 5:7", text: "Give all your worries and cares to God, for he cares about you." },
  { ref: "Revelation 21:4", text: "He will wipe every tear from their eyes, and there will be no more death or sorrow or crying or pain." },
  { ref: "Romans 6:23", text: "For the wages of sin is death, but the free gift of God is eternal life through Christ Jesus our Lord." },
  { ref: "Acts 16:31", text: "They replied, “Believe in the Lord Jesus and you will be saved, along with everyone in your household.”" },
  { ref: "Ephesians 2:8-9", text: "For by grace you have been saved through faith. And this is not your own doing; it is the gift of God, not a result of works, so that no one may boast." },
  { ref: "John 14:6", text: "Jesus told him, “I am the way, the truth, and the life. No one can come to the Father except through me.”" },
  { ref: "Romans 10:9", text: "If you openly declare that Jesus is Lord and believe in your heart that God raised him from the dead, you will be saved." },
  { ref: "1 John 1:9", text: "But if we confess our sins to him, he is faithful and just to forgive us our sins and to cleanse us from all wickedness." },
  { ref: "Lamentations 3:22-23", text: "The faithful love of the Lord never ends! His mercies never cease. Great is his faithfulness; his mercies begin afresh each morning." },
  { ref: "Psalm 136:1", text: "Give thanks to the Lord, for he is good! His faithful love endures forever." },
  { ref: "Romans 8:38-39", text: "And I am convinced that nothing can ever separate us from God’s love. Neither death nor life, neither angels nor demons... not even the powers of hell can separate us from God’s love that is revealed in Christ Jesus our Lord." },
  { ref: "1 John 4:7-8", text: "Dear friends, let us continue to love one another, for love comes from God. Anyone who loves is a child of God and knows God. But anyone who does not love does not know God, for God is love." },
  { ref: "Malachi 3:6", text: "“I am the Lord, and I do not change. That is why you descendants of Jacob are not already destroyed." },
  { ref: "Hebrews 13:8", text: "Jesus Christ is the same yesterday, today, and forever." },
  { ref: "1 Corinthians 10:13", text: "The temptations in your life are no different from what others experience. And God is faithful. He will not allow the temptation to be more than you can handle." },
  { ref: "Psalm 37:4", text: "Take delight in the Lord, and he will give you your heart’s desires." },
  { ref: "Psalm 121:1-2", text: "I look up to the mountains—does my help come from there? My help comes from the Lord, who made heaven and earth!" },
  { ref: "Psalm 34:17", text: "The Lord hears his people when they call to him for help. He rescues them from all their troubles." },
  { ref: "Isaiah 26:3", text: "You will keep in perfect peace all who trust in you, all whose thoughts are fixed on you!" },
  { ref: "2 Corinthians 12:9", text: "Each time he said, “My grace is all you need. My power works best in weakness.” So now I am glad to boast about my weaknesses, so that the power of Christ can work through me." },
  { ref: "Romans 15:13", text: "I pray that God, the source of hope, will fill you completely with joy and peace because you trust in him. Then you will overflow with confident hope through the power of the Holy Spirit." },
  { ref: "John 16:33", text: "I have told you all this so that you may have peace in me. Here on earth you will have many trials and sorrows. But take heart, because I have overcome the world.”" },
  { ref: "Isaiah 53:5", text: "But he was pierced for our rebellion, crushed for our sins. He received the punishment that brought us peace, and with his wounds we are healed." },
  { ref: "Proverbs 4:23", text: "Guard your heart above all else, for it determines the course of your life." },
  { ref: "Psalm 119:105", text: "Your word is a lamp to guide my feet and a light for my path." },
  { ref: "James 1:5", text: "If you need wisdom, ask our generous God, and he will give it to you. He will not rebuke you for asking." },
  { ref: "Matthew 7:7", text: "“Keep on asking, and you will receive what you ask for. Keep on seeking, and you will find. Keep on knocking, and the door will be opened to you." },
  { ref: "Matthew 28:19-20", text: "Therefore, go and make disciples of all the nations, baptizing them in the name of the Father and the Son and the Holy Spirit. Teach these new disciples to obey all the commands I have given you. And be sure of this: I am with you always, even to the end of the age.”" },
  { ref: "1 Corinthians 10:31", text: "So whether you eat or drink, or whatever you do, do it all for the glory of God." },
  { ref: "Colossians 3:23", text: "Work willingly at whatever you do, as though you were working for the Lord rather than for people." },
  { ref: "Micah 6:8", text: "No, O people, the Lord has told you what is good, and this is what he requires of you: to do what is right, to love mercy, and to walk humbly with your God." },
  { ref: "1 Thessalonians 5:16-18", text: "Always be joyful. Never stop praying. Be thankful in all circumstances, for this is God’s will for you who belong to Christ Jesus." },
  { ref: "Galatians 5:22-23", text: "But the Holy Spirit produces this kind of fruit in our lives: love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control." },
  { ref: "Hebrews 12:1", text: "Therefore, since we are surrounded by such a huge crowd of witnesses to the life of faith, let us strip off every weight that slows us down, especially the sin that so easily trips us up. And let us run with endurance the race God has set before us." },
  { ref: "James 4:7", text: "So humble yourselves before God. Resist the devil, and he will flee from you." },
  { ref: "Psalm 46:10", text: "“Be still, and know that I am God! I will be honored by every nation. I will be honored throughout the world.”" },
  { ref: "Romans 12:12", text: "Be joyful in hope, patient in affliction, and faithful in prayer." },
  { ref: "Psalm 42:11", text: "Why am I discouraged? Why is my heart so sad? I will put my hope in God! I will praise him again—my Savior and my God!" },
  { ref: "Jeremiah 17:7", text: "But blessed are those who trust in the Lord and have made the Lord their hope and confidence." },
  { ref: "Psalm 62:5-6", text: "Yes, put your hope in God, for I will praise him as my Savior and my God! He alone is my rock and my salvation, my fortress where I will not be shaken." },
  { ref: "Proverbs 23:18", text: "There is surely a future hope for you, and your hope will not be cut off." },
  { ref: "Hebrews 10:23", text: "Let us hold tightly to the hope we affirm, for God can be trusted to keep his promise." },
  { ref: "Colossians 1:27", text: "For this is the secret: Christ lives in you. This gives you assurance of sharing his glory." },
  { ref: "Philippians 1:6", text: "And I am certain that God, who began the good work within you, will continue his work until it is finally finished on the day when Christ Jesus returns." },
  { ref: "Psalm 31:24", text: "So be strong and courageous, all you who put your hope in the Lord!" },
  { ref: "2 Corinthians 4:17", text: "For our present troubles are small and won’t last very long. Yet they produce for us a glory that vastly outweighs them and will last forever!" },
  { ref: "Psalm 94:19", text: "When doubts filled my mind, your comfort gave me renewed hope and cheer." },
  { ref: "Isaiah 43:2", text: "When you go through deep waters, I will be with you. When you go through rivers of difficulty, you will not drown. When you walk through the fire of oppression, you will not be burned up; the flames will not consume you." },
  { ref: "Psalm 100:4", text: "Enter his gates with thanksgiving; go into his courts with praise. Give thanks to him and praise his name." },
  { ref: "Psalm 103:1", text: "Let all that I am praise the Lord; with my whole heart, I will praise his holy name." },
  { ref: "Psalm 150:6", text: "Let everything that breathes sing praises to the Lord! Praise the Lord!" },
  { ref: "Psalm 9:1", text: "I will praise you, Lord, with all my heart; I will tell of all the marvelous things you have done." },
  { ref: "Psalm 30:11-12", text: "You have turned my mourning into joyful dancing... O Lord my God, I will give you thanks forever!" },
  { ref: "Colossians 3:16", text: "Let the message about Christ, in all its richness, fill your lives. Teach and counsel each other with all the wisdom he gives. Sing psalms and hymns and spiritual songs to God with thankful hearts." },
  { ref: "1 Chronicles 16:23-24", text: "Let the whole earth sing to the Lord! Each day proclaim the good news that he saves. Publish his glorious deeds among the nations. Tell everyone about the amazing things he does." },
  { ref: "Psalm 28:7", text: "The Lord is my strength and shield. I trust him with all my heart. He helps me, and my heart is filled with joy. I burst out in songs of thanksgiving." },
  { ref: "Psalm 145:3", text: "Great is the Lord! He is most worthy of praise! No one can measure his greatness." },
  { ref: "Psalm 103:12", text: "He has removed our sins as far from us as the east is from the west." },
  { ref: "Isaiah 43:25", text: "“I—yes, I alone—will blot out your sins for my own sake and will never think of them again." },
  { ref: "Colossians 3:13", text: "Make allowance for each other's faults, and forgive anyone who offends you. Remember, the Lord forgave you, so you must forgive others." },
  { ref: "Ephesians 4:32", text: "Instead, be kind to each other, tenderhearted, forgiving one another, just as God through Christ has forgiven you." },
  { ref: "Psalm 86:5", text: "O Lord, you are so good, so ready to forgive, so full of unfailing love for all who ask for your help." },
  { ref: "Matthew 6:14-15", text: "“If you forgive those who sin against you, your heavenly Father will also forgive you. But if you refuse to forgive others, your Father will not forgive your sins." },
  { ref: "Micah 7:18-19", text: "Where is another God like you, who pardons the guilt of the remnant, overlooking the sins of his special people? ... You will trample our sins under your feet and throw them into the depths of the ocean!" },
  { ref: "Isaiah 1:18", text: "“Come now, let's settle this,” says the Lord. “Though your sins are like scarlet, I will make them as white as snow." },
  { ref: "Romans 8:1", text: "So now there is no condemnation for those who belong to Christ Jesus." },
  { ref: "Proverbs 1:7", text: "Fear of the Lord is the foundation of true knowledge, but fools despise wisdom and discipline." },
  { ref: "Proverbs 4:7", text: "Getting wisdom is the wisest thing you can do! And whatever else you do, develop good judgment." },
  { ref: "Proverbs 2:6", text: "For the Lord grants wisdom! From his mouth come knowledge and understanding." },
  { ref: "James 3:17", text: "But the wisdom from above is first of all pure. It is also peace loving, gentle at all times, and willing to yield to others. It is full of mercy and good deeds." },
  { ref: "Psalm 32:8", text: "The Lord says, “I will guide you along the best pathway for your life. I will advise you and watch over you.”" },
  { ref: "Proverbs 16:3", text: "Commit your actions to the Lord, and your plans will succeed." },
  { ref: "Proverbs 19:20", text: "Get all the advice and instruction you can, so you will be wise the rest of your life." },
  { ref: "Matthew 7:24", text: "“Anyone who listens to my teaching and follows it is wise, like a person who builds a house on solid rock." },
  { ref: "Psalm 111:10", text: "Fear of the Lord is the foundation of true wisdom. All who obey his commandments will grow in wisdom. Praise him forever!" },
  { ref: "Romans 5:3-5", text: "We can rejoice, too, when we run into problems and trials, for we know that they help us develop endurance. And endurance develops strength of character, and character strengthens our confident hope of salvation." },
  { ref: "James 1:2-4", text: "Dear brothers and sisters, when troubles of any kind come your way, consider it an opportunity for great joy. For you know that when your faith is tested, your endurance has a chance to grow. So let it grow, for when your endurance is fully developed, you will be perfect and complete, needing nothing." },
  { ref: "Galatians 6:9", text: "So let’s not get tired of doing what is good. At just the right time we will reap a harvest of blessing if we don’t give up." },
  { ref: "Hebrews 12:2", text: "We must run with endurance the race that God has set before us. We do this by keeping our eyes on Jesus, the champion who initiates and perfects our faith." },
  { ref: "2 Thessalonians 3:13", text: "As for the rest of you, dear brothers and sisters, never get tired of doing good." },
  { ref: "1 Peter 4:12-13", text: "Dear friends, don’t be surprised at the fiery trials you are going through, as if something strange were happening to you. Instead, be very glad—for these trials are sharing in the suffering of Christ, so that you may have the wonderful joy of seeing his glory revealed to all the world." },
  { ref: "Revelation 3:10", text: "“Because you have obeyed my command to persevere, I will protect you from the great time of testing that will come upon the whole world." },
  { ref: "Romans 12:1", text: "And so, dear brothers and sisters, I plead with you to give your bodies to God because of all he has done for you. Let them be a living and holy sacrifice—the kind he finds acceptable. This is truly the way to worship him." },
  { ref: "2 Peter 3:9", text: "The Lord isn’t really being slow about his promise, as some people think. No, he is being patient for your sake. He does not want anyone to be destroyed, but wants everyone to repent." },
  { ref: "2 Corinthians 1:20", text: "For all of God’s promises have been fulfilled in Christ with a resounding 'Yes!' And through Christ, our 'Amen' (which means 'Yes') ascends to God for his glory." },
  { ref: "Hebrews 6:18", text: "So God has given us both his promise and his oath. These two things are unchangeable because it is impossible for God to lie. Therefore, we who have fled to him for refuge can have great confidence as we hold to the hope that lies before us." },
  { ref: "Joshua 21:45", text: "Not a single one of all the good promises the Lord had given to the family of Israel was left unfulfilled; everything he had spoken came true." },
  { ref: "Psalm 145:13", text: "For your kingdom is an everlasting kingdom. You rule throughout all generations. The Lord is faithful in all he says and kind in all he does." },
  { ref: "Psalm 33:4", text: "For the word of the Lord holds true, and we can trust everything he does." },
  { ref: "1 Kings 8:56", text: "“Praise the Lord who has given rest to his people Israel, just as he promised. Not a single word has failed from all the wonderful promises he gave through his servant Moses." },
  { ref: "Deuteronomy 7:9", text: "Understand, therefore, that the Lord your God is indeed God. He is the faithful God who keeps his covenant for a thousand generations and lavishes his unfailing love on those who love him and obey his commands." },
  { ref: "2 Corinthians 9:7", text: "You must each decide in your heart how much to give. And don’t give reluctantly or in response to pressure. “For God loves a person who gives cheerfully.”" },
  { ref: "Luke 6:38", text: "Give, and you will receive. Your gift will return to you in full—pressed down, shaken together to make room for more, running over, and poured into your lap. The amount you give will determine the amount you get back.”" },
  { ref: "Proverbs 11:24", text: "Give freely and become more wealthy; be stingy and lose everything." },
  { ref: "Acts 20:35", text: "And I have been a constant example of how you can help those in need by working hard. You should remember the words of the Lord Jesus: ‘It is more blessed to give than to receive.’ ”" },
  { ref: "Proverbs 28:27", text: "Whoever gives to the poor will lack nothing, but those who close their eyes to poverty will be cursed." },
  { ref: "Philippians 4:19", text: "And this same God who takes care of me will supply all your needs from his glorious riches, which have been given to us in Christ Jesus." },
  { ref: "1 Timothy 6:18-19", text: "Tell them to use their money to do good. They should be rich in good works and generous to those in need, always being ready to share with others. By doing this they will be storing up real treasure for themselves in heaven—it is the only safe investment for eternity." },
  { ref: "John 10:10", text: "The thief’s purpose is to steal and kill and destroy. My purpose is to give them a rich and satisfying life." },
  { ref: "Matthew 5:3-12", text: "“God blesses those who are poor and realize their need for him, for the Kingdom of Heaven is theirs..." },
  { ref: "Matthew 6:9-13", text: "Pray like this: Our Father in heaven, may your name be kept holy..." },
  { ref: "John 14:1-3", text: "“Don’t let your hearts be troubled. Trust in God, and trust also in me. There is more than enough room in my Father’s home..." },
  { ref: "Luke 19:10", text: "For the Son of Man came to seek and save those who are lost.”" },
  { ref: "John 15:5", text: "“Yes, I am the vine; you are the branches. Those who remain in me, and I in them, will produce much fruit. For apart from me you can do nothing." },
  { ref: "1 Corinthians 15:58", text: "So, my dear brothers and sisters, be strong and immovable. Always work enthusiastically for the Lord, for you know that nothing you do for the Lord is ever useless." },
  { ref: "Ephesians 3:20-21", text: "Now all glory to God, who is able, through his mighty power at work within us, to accomplish infinitely more than we might ask or think. Glory to him in the church and in Christ Jesus through all generations forever and ever! Amen." },
  { ref: "Ephesians 6:10-11", text: "A final word: Be strong in the Lord and in his mighty power. Put on all of God’s armor so that you will be able to stand firm against all strategies of the devil." },
  { ref: "1 John 4:19", text: "We love each other because he loved us first." },
  { ref: "1 John 5:14-15", text: "And we are confident that he hears us whenever we ask for anything that pleases him. And since we know he hears us when we make our requests, we also know that he will give us what we ask for." },
  { ref: "2 Timothy 3:16", text: "All Scripture is inspired by God and is useful to teach us what is true and to make us realize what is wrong in our lives." },
  { ref: "2 Timothy 4:7-8", text: "I have fought the good fight, I have finished the race, and I have remained faithful. And now the prize awaits me—the crown of righteousness..." },
  { ref: "Hebrews 4:12", text: "For the word of God is alive and powerful. It is sharper than the sharpest two-edged sword, cutting between soul and spirit, between joint and marrow. It exposes our innermost thoughts and desires." },
  { ref: "Hebrews 4:16", text: "So let us come boldly to the throne of our gracious God. There we will receive his mercy, and we will find grace to help us when we need it most." },
  { ref: "1 Peter 2:9", text: "But you are not like that, for you are a chosen people. You are royal priests, a holy nation, God’s very own possession. As a result, you can show others the goodness of God, for he called you out of the darkness into his wonderful light." },
  { ref: "Jude 1:24-25", text: "Now all glory to him who is able to keep you from falling away and will bring you with great joy into his glorious presence without a single fault. All glory to him, the only God our Savior, through Jesus Christ our Lord. Amen." },

  // --- NEW BATCH: Psalms, Major Prophets, and Old Testament Law/Covenant ---

  // Popular Psalms (Focusing on Protection, Guidance, and Trust)
  { ref: "Psalm 1:1-3", text: "Oh, the joys of those who do not follow the advice of the wicked... They are like trees planted along the riverbank, bearing fruit each season. Their leaves never wither, and they prosper in all they do." },
  { ref: "Psalm 4:8", text: "I will lie down in peace and sleep, for you alone, O Lord, will keep me safe." },
  { ref: "Psalm 19:14", text: "May the words of my mouth and the meditation of my heart be pleasing to you, O Lord, my rock and my redeemer." },
  { ref: "Psalm 34:8", text: "Taste and see that the Lord is good. Oh, the joys of those who take refuge in him!" },
  { ref: "Psalm 37:23-24", text: "The Lord directs the steps of the godly. He delights in every detail of their lives. Though they stumble, they will never fall, for the Lord holds them by the hand." },
  { ref: "Psalm 51:10", text: "Create in me a clean heart, O God. Renew a loyal spirit within me." },
  { ref: "Psalm 73:26", text: "My health may fail, and my spirit may be weak, but God remains the strength of my heart; he is mine forever." },
  { ref: "Psalm 107:1", text: "Give thanks to the Lord, for he is good! His faithful love endures forever." },
  { ref: "Psalm 118:24", text: "This is the day the Lord has made. We will rejoice and be glad in it." },
  { ref: "Psalm 139:13-14", text: "You made all the delicate, inner parts of my body and knit me together in my mother’s womb. Thank you for making me so wonderfully complex!" },
  { ref: "Psalm 143:8", text: "Let me hear of your unfailing love each morning, for I am trusting you. Show me where to walk, for I give myself to you." },
  { ref: "Psalm 33:12", text: "What joy for the nation whose God is the Lord, whose people he has chosen as his own." },
  { ref: "Psalm 16:11", text: "You will show me the way of life, granting me the joy of your presence and the pleasures of living with you forever." },
  { ref: "Psalm 55:22", text: "Give your burdens to the Lord, and he will take care of you. He will not permit the godly to slip and fall." },
  { ref: "Psalm 90:12", text: "Teach us to realize the brevity of life, so that we may grow in wisdom." },
  { ref: "Psalm 13:5-6", text: "But I trust in your unfailing love. I will rejoice because you have rescued me. I will sing to the Lord because he is good to me." },
  { ref: "Psalm 91:11", text: "For he will order his angels to protect you wherever you go." },
  { ref: "Psalm 3:3", text: "But you, O Lord, are a shield around me; you are my glory, the one who holds my head high." },

  // Major Prophets (Isaiah, Jeremiah - Focusing on Comfort, Future, Sovereignty)
  { ref: "Isaiah 9:6", text: "For a child is born to us, a son is given to us. The government will rest on his shoulders. And he will be called: Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace." },
  { ref: "Isaiah 40:8", text: "The grass withers and the flowers fade, but the word of our God stands forever." },
  { ref: "Isaiah 54:17", text: "But in that coming day, no weapon turned against you will succeed. You will silence every voice raised up to accuse you. These benefits are enjoyed by the servants of the Lord; their vindication will come from me. I, the Lord, have spoken!" },
  { ref: "Isaiah 55:8-9", text: "“My thoughts are nothing like your thoughts,” says the Lord. “And my ways are far beyond anything you could imagine. For just as the heavens are higher than the earth, so my ways are higher than your ways and my thoughts higher than your thoughts." },
  { ref: "Isaiah 60:1", text: "Arise, Jerusalem! Let your light shine for all to see. For the glory of the Lord is shining upon you." },
  { ref: "Jeremiah 33:3", text: "‘Call to me and I will answer you. I will tell you wonderful and amazing things that you know nothing about.’" },
  { ref: "Jeremiah 31:33", text: "“But this is the new covenant I will make with the people of Israel after those days,” says the Lord. “I will put my instructions deep within them, and I will write them on their hearts. I will be their God, and they will be my people." },
  { ref: "Jeremiah 1:5", text: "“I knew you before I formed you in your mother’s womb. Before you were born I set you apart and appointed you as my prophet to the nations.”" },
  { ref: "Lamentations 3:25", text: "The Lord is good to those who wait for him, to all who seek him." },

  // Old Testament Law and Covenant (Key Commandments and Declarations)
  { ref: "Exodus 20:3", text: "“You must not have any other god but me." }, // First Commandment
  { ref: "Exodus 20:12", text: "“Honor your father and mother. Then you will live a long, full life in the land the Lord your God is giving you." }, // Fifth Commandment
  { ref: "Exodus 34:6-7", text: "The Lord! The Lord! A God who is compassionate and gracious, slow to anger, and filled with unfailing love and faithfulness. I lavish unfailing love to a thousand generations." }, // God's Self-Declaration to Moses
  { ref: "Numbers 6:24-26", text: "‘May the Lord bless you and protect you. May the Lord smile on you and be gracious to you. May the Lord show you his favor and give you his peace.’" }, // The Priestly Blessing
  { ref: "Deuteronomy 6:4-5", text: "“Listen, O Israel! The Lord is our God, the Lord alone. And you must love the Lord your God with all your heart, all your soul, and all your strength." }, // The Shema
  { ref: "Deuteronomy 30:19", text: "“Today I have given you the choice between life and death, between blessings and curses. Now I call on heaven and earth to witness the choice you make. Oh, that you would choose life, so that you and your descendants might live!" },
  { ref: "Joshua 24:15", text: "But as for me and my family, we will serve the Lord." },
  { ref: "Genesis 50:20", text: "You intended to harm me, but God intended it all for good. He brought me to this position so I could save the lives of many people." },
  { ref: "1 Samuel 16:7", text: "The Lord doesn’t see things the way you see them. People judge by outward appearance, but the Lord looks at the heart." },
  { ref: "2 Chronicles 7:14", text: "Then if my people who are called by my name will humble themselves and pray and seek my face and turn from their wicked ways, I will hear from heaven and will forgive their sins and restore their land." },

  // Bonus: More Popular Verses to hit the target faster
  { ref: "Psalm 127:3", text: "Children are a gift from the Lord; they are a reward from him." },
  { ref: "Proverbs 22:6", text: "Direct your children onto the right path, and when they are older, they will not leave it." },
  { ref: "Psalm 92:4", text: "You thrill me, Lord, with all you have done for me! I sing for joy at the works of your hands." },
  { ref: "Isaiah 25:1", text: "O Lord, I will honor and praise your name, for you have done wonderful things. You have planned them long ago, and you have carried them out with perfect faithfulness." },
  { ref: "Zephaniah 3:17", text: "For the Lord your God is living among you. He is a mighty savior. He will take delight in you with gladness. With his love, he will calm all your fears. He will rejoice over you with joyful songs.”" },
  { ref: "Matthew 18:20", text: "For where two or three gather together as my followers, I am there among them." },
  { ref: "Luke 1:37", text: "For nothing is impossible with God." },
  { ref: "Romans 1:16", text: "For I am not ashamed of this Good News about Christ. It is the power of God at work, saving everyone who believes—the Jew first and also the Gentile." },
  { ref: "1 Corinthians 6:19-20", text: "Don’t you realize that your body is the temple of the Holy Spirit, who lives in you and was given to you by God? You do not belong to yourself, for God bought you with a high price. So you must honor God with your body." },
  { ref: "2 Corinthians 5:21", text: "For God made Christ, who never sinned, to be the offering for our sin, so that we could be made right with God through Christ." },
  { ref: "Galatians 2:20", text: "My old self has been crucified with Christ. It is no longer I who live, but Christ lives in me. So I live in this earthly body by trusting in the Son of God, who loved me and gave himself for me." },
  { ref: "Ephesians 5:25", text: "For husbands, this means love your wives, just as Christ loved the church. He gave up his life for her." },
  { ref: "Hebrews 11:6", text: "And it is impossible to please God without faith. Anyone who wants to come to him must believe that God exists and that he rewards those who sincerely seek him." },
  { ref: "1 Peter 3:15", text: "Instead, you must set apart Christ as Lord in your hearts. And always be ready to give an explanation to anyone who asks you about the hope you have." },
  { ref: "1 John 4:4", text: "But you belong to God, my dear children. You have already won a victory over those people, because the Spirit who lives in you is greater than the spirit who lives in the world." },
{ ref: "Hosea 6:6", text: "I want you to show love, not offer sacrifices. I want you to know me more than I want burnt offerings." },
{ ref: "Joel 2:28-29", text: "“Then, after doing all those things, I will pour out my Spirit upon all people. Your sons and daughters will prophesy, your old men will dream dreams, and your young men will see visions. In those days, I will pour out my Spirit even on servants—men and women alike." },
{ ref: "Amos 5:24", text: "Instead, let justice roll down like water, and righteousness like an ever-flowing stream." },
{ ref: "Micah 6:8", text: "No, O people, the Lord has told you what is good, and this is what he requires of you: to do what is right, to love mercy, and to walk humbly with your God." },
{ ref: "Habakkuk 2:4", text: "“Look at the proud! They trust in themselves, and their lives are crooked. But the righteous will live by their faithfulness to God." },
{ ref: "Habakkuk 3:17-18", text: "Even though the fig trees have no blossoms, and there are no grapes on the vines; even though the olive crop fails, and the fields lie empty and barren; even though the flocks die in the fields, and the cattle barns are empty, yet I will rejoice in the Lord! I will be joyful in the God of my salvation!" },
{ ref: "Zephaniah 3:17", text: "For the Lord your God is living among you. He is a mighty savior. He will take delight in you with gladness. With his love, he will calm all your fears. He will rejoice over you with joyful songs.”" },
{ ref: "Haggai 2:9", text: "‘The future glory of this Temple will be greater than its past glory,’ says the Lord of Heaven’s Armies. ‘And in this place I will give peace.’ This is the declaration of the Lord of Heaven’s Armies." },
{ ref: "Malachi 3:10", text: "Bring all the tithes into the storehouse so there will be enough food in my Temple. If you do, says the Lord of Heaven’s Armies, I will open the windows of heaven for you. I will pour out a blessing so great you won’t have enough room to take it all in!" },
{ ref: "Zechariah 4:6", text: "Then he said to me, 'This is the message of the Lord to Zerubbabel: It is not by military might nor by physical strength, but by my Spirit,' says the Lord of Heaven’s Armies." },
{ ref: "Jonah 2:9", text: "But I will offer sacrifices to you with shouts of praise, and I will fulfill my vows. For my salvation comes from the Lord alone.”" },

// Historical/Narrative Books (Genesis, Kings, Chronicles, Ezra, Nehemiah, Samuel, Judges)
{ ref: "Genesis 12:2-3", text: "I will make you into a great nation. I will bless you and make you famous, and you will be a blessing to others. I will bless those who bless you and curse those who treat you with contempt. All the families on earth will be blessed through you.”" },
{ ref: "Exodus 33:14", text: "The Lord replied, “I will personally go with you, Moses, and I will give you rest.”" },
{ ref: "Leviticus 19:18", text: "“Do not seek revenge or hold a grudge against an a member of your community. Instead, love your neighbor as yourself. I am the Lord." },
{ ref: "Numbers 23:19", text: "God is not a man, so he does not lie. He is not human, so he does not change his mind. Has he ever spoken and failed to act? Has he ever promised and not carried it through?" },
{ ref: "Judges 6:12", text: "The angel of the Lord appeared to him and said, 'Mighty hero, the Lord is with you!'" },
{ ref: "1 Samuel 2:6", text: "The Lord kills and makes alive. He brings some down to the grave but raises others up." },
{ ref: "1 Samuel 15:22", text: "What is more pleasing to the Lord: your burnt offerings and sacrifices or your obedience to his voice? Listen! Obedience is better than sacrifice, and submission is better than offering the fat of rams." },
{ ref: "2 Samuel 7:28", text: "For you are God, O Sovereign Lord. Your words are truth, and you have promised these good things to me, your servant." },
{ ref: "1 Kings 8:61", text: "And may you remain completely loyal to the Lord our God. May you always obey his decrees and commands, just as you are doing today.”" },
{ ref: "2 Chronicles 16:9", text: "The eyes of the Lord search the whole earth in order to strengthen those whose hearts are fully committed to him." },
{ ref: "Nehemiah 8:10", text: "Don’t sorrow, for the joy of the Lord is your strength.”" },
{ ref: "Ezra 8:23", text: "So we fasted and earnestly prayed that our God would protect us, and he answered our prayer." },

// More Proverbs & Ecclesiastes (Wisdom, Conduct, Life)
{ ref: "Proverbs 10:19", text: "Too much talk leads to sin. Be sensible and keep your mouth shut." },
{ ref: "Proverbs 13:3", text: "Those who control their tongue will have a long life; opening your mouth can ruin everything." },
{ ref: "Proverbs 14:12", text: "There is a path before each person that seems right, but it ends in death." },
{ ref: "Proverbs 15:1", text: "A gentle answer deflects anger, but harsh words make tempers flare." },
{ ref: "Proverbs 15:13", text: "A glad heart makes a happy face; a broken heart makes for a crushed spirit." },
{ ref: "Proverbs 16:9", text: "We can make our plans, but the Lord determines our steps." },
{ ref: "Proverbs 17:17", text: "A friend is always loyal, and a brother is born to help in time of need." },
{ ref: "Proverbs 18:10", text: "The name of the Lord is a strong fortress; the godly run to him and are safe." },
{ ref: "Proverbs 21:23", text: "If you keep your mouth shut, you will stay out of trouble." },
{ ref: "Proverbs 22:1", text: "Choose a good reputation over great riches; being held in high esteem is better than silver or gold." },
{ ref: "Proverbs 27:1", text: "Don’t brag about tomorrow, since you don’t know what the day will bring." },
{ ref: "Proverbs 27:17", text: "As iron sharpens iron, so a friend sharpens a friend." },
{ ref: "Proverbs 28:13", text: "People who conceal their sins will not prosper, but if they confess and turn from them, they will receive mercy." },
{ ref: "Ecclesiastes 3:1", text: "For everything there is a season, a time for every activity under heaven." },
{ ref: "Ecclesiastes 4:9-10", text: "Two people are better off than one, for they can help each other succeed. If one person falls, the other can reach out and help. But someone who falls alone is in real trouble." },
{ ref: "Ecclesiastes 9:11", text: "I have observed something else under the sun. The fastest runner doesn’t always win the race, and the strongest warrior doesn’t always win the battle... but time and chance happen to them all." },
{ ref: "Ecclesiastes 12:13", text: "That’s the whole story. Here now is my final conclusion: Fear God and obey his commands, for this is everyone’s duty." },

// Bonus Verses (To solidify the 350+ count)
{ ref: "Psalm 126:5-6", text: "Those who plant in tears will harvest with shouts of joy. They weep as they go to plant their seed, but they sing as they return with the harvest." },
{ ref: "Psalm 138:8", text: "The Lord will work out his plans for my life—for your faithful love, O Lord, endures forever. Don’t abandon me, for you made me." },
{ ref: "Proverbs 3:9-10", text: "Honor the Lord with your wealth and with the best part of everything you produce. Then he will fill your barns with grain, and your vats will overflow with good wine." },
{ ref: "Isaiah 58:11", text: "The Lord will guide you continually, giving you water when you are dry and restoring your strength. You will be like a well-watered garden, like an ever-flowing spring." },
{ ref: "Matthew 10:39", text: "If you cling to your life, you will lose it; but if you give up your life for me, you will find it." },
{ ref: "Mark 10:45", text: "For even the Son of Man came not to be served but to serve others and to give his life as a ransom for many.”" },
{ ref: "Luke 12:34", text: "Wherever your treasure is, there the desires of your heart will also be." },
{ ref: "Acts 4:12", text: "There is salvation in no one else! God has given no other name under heaven by which we must be saved.”" },
{ ref: "Romans 5:8", text: "But God showed his great love for us by sending Christ to die for us while we were still sinners." },
{ ref: "Romans 13:10", text: "Love does no wrong to others, so love fulfills the requirements of God’s law." },
{ ref: "1 Corinthians 15:33", text: "Don’t be fooled by those who say such things, for 'bad company corrupts good character.'" },
{ ref: "Galatians 6:7", text: "Don’t be misled—you cannot mock the justice of God. You will always harvest what you plant." },
{ ref: "Ephesians 5:20", text: "And give thanks for everything to God the Father in the name of our Lord Jesus Christ." },
{ ref: "Colossians 3:17", text: "And whatever you do or say, do it as a representative of the Lord Jesus, giving thanks through him to God the Father." },
{ ref: "1 Timothy 6:10", text: "For the love of money is the root of all kinds of evil. And some people, craving money, have wandered from the true faith and pierced themselves with many sorrows." },
{ ref: "James 1:19-20", text: "Understand this, my dear brothers and sisters: You must all be quick to listen, slow to speak, and slow to get angry. Human anger does not produce the righteousness God desires." },
{ ref: "1 Peter 4:8", text: "Most important of all, continue to show deep love for each other, for love covers a multitude of sins." },
{ ref: "Revelation 1:8", text: "“I am the Alpha and the Omega—the beginning and the end,” says the Lord God. “I am the one who is, who always was, and who is still to come—the Almighty.”" },
{ ref: "Revelation 22:20", text: "He who is the faithful witness says, “Yes, I am coming soon!” Amen! Come, Lord Jesus!" },
];
